Implementation of service
wearesho-team/phonet pull request #1
Opened 2019-01-18 15:51 UTC by KartaviK

2019-01-21 17:11 UTC, Horat1us requested changes

2019-01-21 17:11 UTC, Horat1us commented on src/Service.php
> +        GuzzleHttp\ClientInterface $client,
Change arguments to config -> provider -> client

2019-01-24 09:48 UTC, sashabeton requested changes

2019-01-24 09:48 UTC, sashabeton commented on src/Authorization/CacheException.php
> +class CacheException extends \RuntimeException
Override `toString()` to receive correct error descriptions

2019-01-24 09:48 UTC, sashabeton commented on src/Authorization/CacheProvider.php
> +    protected function cacheResponse(string $cacheKey, GuzzleHttp\Cookie\CookieJarInterface $response)
Add return type for elegance

2019-01-24 15:44 UTC, sashabeton requested changes

2019-01-24 15:44 UTC, sashabeton commented on src/Authorization/CacheProvider.php
> +        if (!$cached instanceof GuzzleHttp\Cookie\CookieJarInterface || !$this->cache->has($cacheKey)) {
Remove useless second condition

2019-01-28 16:12 UTC, Horat1us requested changes

2019-01-28 16:12 UTC, Horat1us commented on composer.json
> +        "phpunit/phpunit": "^7.5",
Why not dev dependencies?

2019-01-28 16:12 UTC, Horat1us commented on src/Config.php
> +        ClientInterface $client,
Should be used as GuzzleHttp\ClientInterface, because `ClientInterface` is too common.

2019-01-28 16:12 UTC, Horat1us commented on src/Data/ActiveCall.php
> +        ?Collection\Subject $subjects,
Необязательные аргументы в конец.

2019-01-28 16:12 UTC, Horat1us commented on src/Model.php
> +    protected function send(GuzzleHttp\Psr7\Request $request): ResponseInterface
А почему не вынести это в отдельный класс, который будет отправлять запросы? Тогда не нужны будут тесты для абстрактных классов, а тесты собственно репозитория и сервиса можно будет мокать без использования Guzzle. И зависимости авторизации/конфига как раз передавать в сервис, который уже отправляет запросы. Тогда Repository\Service будут заниматься формированием и парсингом запроса, которые у всех разные.

2019-01-28 19:54 UTC, Horat1us approved these changes

2019-01-28 19:54 UTC, merged